spring.datasource.url=${JLTS_DATASOURCE_URL}
spring.datasource.username=${JLTS_DATASOURCE_USERNAME}
spring.datasource.password=${JLTS_DATASOURCE_PASSWORD}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

